#!/bin/bash
# Orchestrator Environment Setup
# Run this once to create your .env file from existing credentials

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
CREDS_FILE="$SCRIPT_DIR/../TicketManagement/airtable-fetcher/credentials.env"

echo "🔧 Orchestrator Environment Setup"
echo "================================="

# Check if .env already exists
if [[ -f "$ENV_FILE" ]]; then
    echo "⚠️  .env already exists at: $ENV_FILE"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env"
        exit 0
    fi
fi

# Start with template
cat > "$ENV_FILE" << 'EOF'
# Orchestrator Configuration
# Auto-generated by setup-env.sh
# This file is in .gitignore - never commit it!

# =============================================================================
# LLM Provider (required - at least one)
# =============================================================================
EOF

# Prompt for Anthropic key
echo ""
read -p "Enter ANTHROPIC_API_KEY (or press Enter to skip): " ANTHROPIC_KEY
if [[ -n "$ANTHROPIC_KEY" ]]; then
    echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY" >> "$ENV_FILE"
else
    echo "# ANTHROPIC_API_KEY=your-key-here" >> "$ENV_FILE"
fi

# Prompt for OpenAI key
read -p "Enter OPENAI_API_KEY (or press Enter to skip): " OPENAI_KEY
if [[ -n "$OPENAI_KEY" ]]; then
    echo "OPENAI_API_KEY=$OPENAI_KEY" >> "$ENV_FILE"
else
    echo "# OPENAI_API_KEY=your-key-here" >> "$ENV_FILE"
fi

# Add model and safety settings
cat >> "$ENV_FILE" << 'EOF'

# Default model
DEFAULT_MODEL=claude-opus-4-20250514

# Safety settings
REQUIRE_APPROVAL=true

# =============================================================================
# Harvest Time Tracking
# =============================================================================
EOF

# Import Harvest credentials from TicketManagement if available
if [[ -f "$CREDS_FILE" ]]; then
    echo ""
    echo "📋 Found existing credentials at: $CREDS_FILE"
    
    HARVEST_TOKEN=$(grep '^HARVEST_ACCESS_TOKEN=' "$CREDS_FILE" 2>/dev/null | cut -d'=' -f2-)
    HARVEST_ACCOUNT=$(grep '^HARVEST_ACCOUNT_ID=' "$CREDS_FILE" 2>/dev/null | cut -d'=' -f2-)
    AIRTABLE_TOKEN=$(grep '^AIRTABLE_PERSONAL_ACCESS_TOKEN=' "$CREDS_FILE" 2>/dev/null | cut -d'=' -f2-)
    AIRTABLE_BASE=$(grep '^AIRTABLE_BASE_ID=' "$CREDS_FILE" 2>/dev/null | cut -d'=' -f2-)
    AIRTABLE_TABLE=$(grep '^AIRTABLE_TABLE_ID=' "$CREDS_FILE" 2>/dev/null | cut -d'=' -f2-)
    
    if [[ -n "$HARVEST_TOKEN" ]]; then
        echo "HARVEST_ACCESS_TOKEN=$HARVEST_TOKEN" >> "$ENV_FILE"
        echo "  ✓ Imported HARVEST_ACCESS_TOKEN"
    fi
    if [[ -n "$HARVEST_ACCOUNT" ]]; then
        echo "HARVEST_ACCOUNT_ID=$HARVEST_ACCOUNT" >> "$ENV_FILE"
        echo "  ✓ Imported HARVEST_ACCOUNT_ID"
    fi
    
    # Add Airtable section
    cat >> "$ENV_FILE" << 'EOF'

# =============================================================================
# Airtable (Ticket Management)
# =============================================================================
EOF
    
    if [[ -n "$AIRTABLE_BASE" ]]; then
        echo "AIRTABLE_BASE_ID=$AIRTABLE_BASE" >> "$ENV_FILE"
        echo "  ✓ Imported AIRTABLE_BASE_ID"
    fi
    if [[ -n "$AIRTABLE_TABLE" ]]; then
        echo "AIRTABLE_TABLE_ID=$AIRTABLE_TABLE" >> "$ENV_FILE"
        echo "  ✓ Imported AIRTABLE_TABLE_ID"
    fi
    if [[ -n "$AIRTABLE_TOKEN" ]]; then
        echo "AIRTABLE_PERSONAL_ACCESS_TOKEN=$AIRTABLE_TOKEN" >> "$ENV_FILE"
        echo "  ✓ Imported AIRTABLE_PERSONAL_ACCESS_TOKEN"
    fi
else
    echo ""
    echo "⚠️  No existing credentials found at: $CREDS_FILE"
    cat >> "$ENV_FILE" << 'EOF'
# HARVEST_ACCESS_TOKEN=your-token
# HARVEST_ACCOUNT_ID=your-account-id
EOF
fi

# Add Upwork sync section
cat >> "$ENV_FILE" << 'EOF'

# =============================================================================
# Upwork Sync (optional - for accounting tools)
# =============================================================================
UPWORK_SYNC_URL=http://localhost:8080
EOF

echo ""
echo "✅ Created: $ENV_FILE"
echo ""
echo "📝 Next steps:"
echo "   1. Edit $ENV_FILE to add any missing API keys"
echo "   2. Run: cd $SCRIPT_DIR && source .env"
echo "   3. Start the orchestrator: streamlit run app.py"
echo ""
echo "⚠️  Remember: .env is in .gitignore - it won't be tracked by git"
echo "   Back it up separately if needed!"
